create table if not exists public.presentations (
  id uuid primary key default gen_random_uuid(),
  salesperson_id uuid not null references public.salespeople(id),
  title text not null default 'Apresentação Institucional ViaGate',
  status text not null default 'draft' check (status in ('draft', 'published', 'expired')),
  current_version integer not null default 0 check (current_version >= 0),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.presentation_versions (
  id uuid primary key default gen_random_uuid(),
  presentation_id uuid not null references public.presentations(id) on delete cascade,
  version_number integer not null check (version_number > 0),
  public_token uuid not null unique default gen_random_uuid(),
  content jsonb not null default '{}'::jsonb,
  published_at timestamptz,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  unique (presentation_id, version_number)
);

create table if not exists public.shared_document_events (
  id bigint generated by default as identity primary key,
  document_kind text not null check (document_kind in ('presentation', 'proposal')),
  presentation_version_id uuid references public.presentation_versions(id) on delete cascade,
  proposal_version_id uuid references public.proposal_versions(id) on delete cascade,
  session_id uuid not null,
  event_type text not null check (event_type in ('open', 'start', 'slide_view', 'complete')),
  slide_number integer,
  slide_total integer,
  created_at timestamptz not null default now(),
  check (
    (document_kind = 'presentation' and presentation_version_id is not null and proposal_version_id is null)
    or
    (document_kind = 'proposal' and proposal_version_id is not null and presentation_version_id is null)
  ),
  check (slide_number is null or slide_number > 0),
  check (slide_total is null or slide_total > 0)
);

create index if not exists presentations_created_by_idx on public.presentations(created_by, updated_at desc);
create index if not exists presentation_versions_presentation_id_idx on public.presentation_versions(presentation_id, version_number desc);
create index if not exists shared_document_events_presentation_idx on public.shared_document_events(presentation_version_id, created_at desc);
create index if not exists shared_document_events_proposal_idx on public.shared_document_events(proposal_version_id, created_at desc);

create unique index if not exists shared_document_events_dedupe_idx
on public.shared_document_events (
  document_kind,
  coalesce(presentation_version_id, proposal_version_id),
  session_id,
  event_type,
  coalesce(slide_number, 0)
);

drop trigger if exists presentations_set_updated_at on public.presentations;
create trigger presentations_set_updated_at
before update on public.presentations
for each row execute function public.set_updated_at();

drop trigger if exists presentation_versions_immutable on public.presentation_versions;
create trigger presentation_versions_immutable
before update or delete on public.presentation_versions
for each row execute function public.prevent_published_version_mutation();

alter table public.presentations enable row level security;
alter table public.presentation_versions enable row level security;
alter table public.shared_document_events enable row level security;

drop policy if exists presentations_select_own on public.presentations;
create policy presentations_select_own
on public.presentations for select
to authenticated
using (created_by = auth.uid());

drop policy if exists presentations_insert_own on public.presentations;
create policy presentations_insert_own
on public.presentations for insert
to authenticated
with check (created_by = auth.uid());

drop policy if exists presentations_update_own on public.presentations;
create policy presentations_update_own
on public.presentations for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

drop policy if exists presentations_delete_own on public.presentations;
create policy presentations_delete_own
on public.presentations for delete
to authenticated
using (created_by = auth.uid());

drop policy if exists presentation_versions_select_own on public.presentation_versions;
create policy presentation_versions_select_own
on public.presentation_versions for select
to authenticated
using (
  exists (
    select 1
    from public.presentations presentation
    where presentation.id = presentation_id
      and presentation.created_by = auth.uid()
  )
);

drop policy if exists presentation_versions_insert_own on public.presentation_versions;
create policy presentation_versions_insert_own
on public.presentation_versions for insert
to authenticated
with check (
  created_by = auth.uid()
  and published_at is null
  and exists (
    select 1
    from public.presentations presentation
    where presentation.id = presentation_id
      and presentation.created_by = auth.uid()
  )
);

drop policy if exists presentation_versions_update_draft_own on public.presentation_versions;
create policy presentation_versions_update_draft_own
on public.presentation_versions for update
to authenticated
using (
  published_at is null
  and exists (
    select 1
    from public.presentations presentation
    where presentation.id = presentation_id
      and presentation.created_by = auth.uid()
  )
)
with check (published_at is null and created_by = auth.uid());

drop policy if exists presentation_versions_delete_draft_own on public.presentation_versions;
create policy presentation_versions_delete_draft_own
on public.presentation_versions for delete
to authenticated
using (
  published_at is null
  and exists (
    select 1
    from public.presentations presentation
    where presentation.id = presentation_id
      and presentation.created_by = auth.uid()
  )
);

drop policy if exists shared_document_events_select_own on public.shared_document_events;
create policy shared_document_events_select_own
on public.shared_document_events for select
to authenticated
using (
  (
    presentation_version_id is not null
    and exists (
      select 1
      from public.presentation_versions version
      join public.presentations presentation on presentation.id = version.presentation_id
      where version.id = presentation_version_id
        and presentation.created_by = auth.uid()
    )
  )
  or
  (
    proposal_version_id is not null
    and exists (
      select 1
      from public.proposal_versions version
      join public.proposals proposal on proposal.id = version.proposal_id
      where version.id = proposal_version_id
        and proposal.created_by = auth.uid()
    )
  )
);

create or replace function public.publish_presentation_version(target_version_id uuid)
returns table (
  public_token uuid,
  published_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_version public.presentation_versions%rowtype;
  target_presentation public.presentations%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select version.*
  into target_version
  from public.presentation_versions version
  join public.presentations presentation on presentation.id = version.presentation_id
  where version.id = target_version_id
    and presentation.created_by = auth.uid();

  if not found then
    raise exception 'Presentation version not found';
  end if;

  if target_version.published_at is null then
    update public.presentation_versions
    set published_at = now()
    where id = target_version_id
    returning * into target_version;
  end if;

  update public.presentations
  set status = 'published',
      current_version = target_version.version_number,
      updated_at = now()
  where id = target_version.presentation_id
    and created_by = auth.uid()
  returning * into target_presentation;

  return query
  select target_version.public_token, target_version.published_at;
end;
$$;

create or replace function public.get_public_presentation(presentation_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'presentation', jsonb_build_object(
      'id', presentation.id,
      'title', presentation.title,
      'status', presentation.status,
      'current_version', presentation.current_version
    ),
    'version', jsonb_build_object(
      'version_number', version.version_number,
      'content', version.content,
      'published_at', version.published_at
    )
  )
  from public.presentation_versions version
  join public.presentations presentation on presentation.id = version.presentation_id
  where version.public_token = presentation_token
    and version.published_at is not null
  limit 1;
$$;

create or replace function public.track_shared_document_event(
  document_kind text,
  document_token uuid,
  event_name text,
  viewer_session uuid,
  slide_number integer default null,
  slide_total integer default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  resolved_presentation_version uuid;
  resolved_proposal_version uuid;
begin
  if document_kind not in ('presentation', 'proposal') then
    return false;
  end if;

  if event_name not in ('open', 'start', 'slide_view', 'complete') then
    return false;
  end if;

  if viewer_session is null then
    return false;
  end if;

  if document_kind = 'presentation' then
    select id
    into resolved_presentation_version
    from public.presentation_versions
    where public_token = document_token
      and published_at is not null;

    if resolved_presentation_version is null then
      return false;
    end if;
  else
    select id
    into resolved_proposal_version
    from public.proposal_versions
    where public_token = document_token
      and published_at is not null;

    if resolved_proposal_version is null then
      return false;
    end if;
  end if;

  insert into public.shared_document_events (
    document_kind,
    presentation_version_id,
    proposal_version_id,
    session_id,
    event_type,
    slide_number,
    slide_total
  ) values (
    document_kind,
    resolved_presentation_version,
    resolved_proposal_version,
    viewer_session,
    event_name,
    slide_number,
    slide_total
  )
  on conflict do nothing;

  return true;
end;
$$;

create or replace function public.get_my_shared_document_stats()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with documents as (
    select
      'presentation'::text as document_kind,
      presentation.id as document_id,
      presentation.title,
      null::text as client_name,
      version.id as version_id,
      version.version_number,
      version.public_token,
      version.published_at
    from public.presentations presentation
    join public.presentation_versions version
      on version.presentation_id = presentation.id
     and version.version_number = presentation.current_version
     and version.published_at is not null
    where presentation.created_by = auth.uid()

    union all

    select
      'proposal'::text as document_kind,
      proposal.id as document_id,
      proposal.title,
      client.company_name as client_name,
      version.id as version_id,
      version.version_number,
      version.public_token,
      version.published_at
    from public.proposals proposal
    join public.clients client on client.id = proposal.client_id
    join public.proposal_versions version
      on version.proposal_id = proposal.id
     and version.version_number = proposal.current_version
     and version.published_at is not null
    where proposal.created_by = auth.uid()
  ),
  stats as (
    select
      document.document_kind,
      document.document_id,
      document.title,
      document.client_name,
      document.version_number,
      document.public_token,
      document.published_at,
      count(*) filter (where event.event_type = 'open')::int as opens,
      count(*) filter (where event.event_type = 'start')::int as starts,
      count(*) filter (where event.event_type = 'complete')::int as completions,
      max(event.created_at) filter (where event.event_type = 'open') as last_opened_at,
      coalesce(
        max(
          case
            when event.event_type = 'slide_view' and event.slide_total > 0
            then round((event.slide_number::numeric / event.slide_total::numeric) * 100)
            else 0
          end
        ),
        0
      )::int as max_progress
    from documents document
    left join public.shared_document_events event
      on (
        document.document_kind = 'presentation'
        and event.presentation_version_id = document.version_id
      )
      or (
        document.document_kind = 'proposal'
        and event.proposal_version_id = document.version_id
      )
    group by
      document.document_kind,
      document.document_id,
      document.title,
      document.client_name,
      document.version_number,
      document.public_token,
      document.published_at
  )
  select coalesce(jsonb_agg(to_jsonb(stats) order by stats.published_at desc), '[]'::jsonb)
  from stats;
$$;

grant select, insert, update, delete on table public.presentations to authenticated;
grant select, insert, update, delete on table public.presentation_versions to authenticated;
grant select on table public.shared_document_events to authenticated;

revoke all on table public.presentations from anon;
revoke all on table public.presentation_versions from anon;
revoke all on table public.shared_document_events from anon;

revoke all on function public.publish_presentation_version(uuid) from public;
grant execute on function public.publish_presentation_version(uuid) to authenticated;

revoke all on function public.get_public_presentation(uuid) from public;
grant execute on function public.get_public_presentation(uuid) to anon, authenticated;

revoke all on function public.track_shared_document_event(text, uuid, text, uuid, integer, integer) from public;
grant execute on function public.track_shared_document_event(text, uuid, text, uuid, integer, integer) to anon, authenticated;

revoke all on function public.get_my_shared_document_stats() from public;
grant execute on function public.get_my_shared_document_stats() to authenticated;